### PR TITLE
corrige la sintaxis para macOS

### PR DESCRIPTION
**Pull request by jvtrudel**
Permite espacios en los PATH

### CODE REVIEW

**Review by samuelsads — COMMENTED** [review]
Hola intente correr los comandos con el PR el primer comando corrió sin problema(./dev up), al intentar correr el segundo comando(./dev sh nous g vitrine_web) me arroja el siguiente error:
/usr/lib/ruby/gems/3.1.0/gems/mustache-1.1.1/bin/mustache:87:in `read': closed stream (IOError)
	from /usr/lib/ruby/gems/3.1.0/gems/mustache-1.1.1/bin/mustache:87:in `process_files'
	from /usr/lib/ruby/gems/3.1.0/gems/mustache-1.1.1/bin/mustache:102:in `<top (required)>'
	from /usr/bin/mustache:25:in `load'
	from /usr/bin/mustache:25:in `<main>'

**Comment by jvtrudel** [comment]
If you type `./dev up`, you are logged in the container?
Have you destroyed the former installed version? You can do this with `./dev down`

The good news is not an error of bash sintaxis en MacOS. :-)
But it look like you do not execute `nous` inside the container.

**Comment by jvtrudel** [comment]
You can use the option `-d` to run bash in debug mode:

```
./dev -d up
```

**Comment by jvtrudel** [comment]
No parece ser útil

**Pull request closed without merging**
